name: Test official Chik Docker Image

on:
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: 'tag'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: 'Chik-Network',
              repo: 'chik-blockchain',
            });
            return release.data.tag_name;

      - run: docker build --build-arg BRANCH="${{ steps.tag.outputs.result }}" .
